language: rust
sudo: false
matrix:
  include:
    - rust: 1.15.0
    - rust: stable
      env:
      - NODEFAULT=1
      - FEATURES="std-vec std-string"
    - rust: beta
    - rust: nightly
      env:
      - FEATURES='unstable'
      - FEATURES="std-vec std-string"
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      ([ "$NODEFAULT" != 1 ] || cargo build --verbose --no-default-features) &&
      (cargo test --verbose --features "$FEATURES" || [ "$TESTFAILOK" = 1 ]) &&
      (cargo test --release --verbose --features "$FEATURES" || [ "$TESTFAILOK" = 1 ]) &&
      cargo doc --verbose --features "$FEATURES"
