language: rust
sudo: false
matrix:
  include:
    - rust: 1.0.0
    - rust: 1.1.0
    - rust: 1.2.0
    - rust: stable
    - rust: beta
    - rust: nightly
      env:
      - FEATURES='unstable'
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      cargo test --release --verbose --features "$FEATURES" &&
      cargo doc --verbose --features "$FEATURES"
